version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
          interval: daily
  - package-ecosystem: cargo
    directory: /actors
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /derive
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /generate
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /macros
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /scsys
    schedule:
      interval: daily
