version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    directory: /scsys
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /actors
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /derive
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /macros
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /utils
    schedule:
      interval: weekly
