version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /core
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /scsys
    schedule:
      interval: daily