version: 2
updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: cargo
    schedule:
      interval: monthly
    directories: 
      - /
      - /scsys
      - /cnf
      - /core
      - /derive
      - /macros
      - /traits
      - /utils
