tasks:
  - init: |
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi --toolchain nightly
      cargo build --release --target wasm32-unknown-unknown --workspace
      cargo build --release --target wasm32-wasi --workspace
    command: cargo xtask auto
