tasks:
  - init: |
      rustup default nightly
      rustup target add wasm32-unknown-unknown wasm32-wasi
      rustup component add clippy rustfmt
      cargo build --release --workspace
      cargo build --target wasm32-unknown-unknown --release --workspace
    command: cargo test --all --all-features -v


