[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = ["network-programming"]
description = "scsys"
edition = "2021"
homepage = "https://scattered-systems.github.io/scsys/"
keywords = ["scsys", "toolkit"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.2"

[features]
default = []
full = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
async-trait = "0.1.56"
axum = "0.5.13"
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
clap = "3.2.12"
config = "0.13.1"
http = "0.2.8"
serde = { features = ["derive"], version = "1.0.139" }
serde_json = "1.0.82"
tokio = { features = ["full"], version = "1.20.0" }
tower = "0.4.13"
tower-http = { features = ["compression-br", "propagate-header", "sensitive-headers", "trace"], version = "0.3.4" }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]