[package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems (https://scattered-systems.com)"]
categories = ["network-programming"]
description = "scsys"
edition = "2021"
homepage = "https://scattered-systems.github.io/scsys/"
keywords = ["scsys", "toolkit"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.7" # TODO: Update the package version

[features]
default = []
full = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
async-trait = "0.1.56"
bson = { features = ["chrono-0_4", "serde_with"], version = "2.3.0" }
chrono = "0.4.19"
config = "0.13.1"
futures = "0.3.21"
glob = "0.3.0"
lazy_static = "1.4.0"
serde = { features = ["derive"], version = "1.0.139" }
serde_json = "1.0.82"

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]