[workspace.package]
authors = [ "FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems <support@scsys.io> (https://github.com/scattered-systems)" ]
categories = [  ]
description = "scsys is a collection of primitives and utilities for use throughout the ecosystem."
edition = "2024"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = [ "primitives", "scsys", "toolkit", "utilities" ]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys.git"
version = "0.2.4"

[workspace]
default-members = [
    "scsys",
]

exclude = [  ]

members = [
    "core",
    "derive",
    "macros",
    "scsys",
    "utils",
]

resolver = "3"

[workspace.dependencies]
# project
scsys-core = { default-features = false, path = "./core", version = "0.2.4" }
# shared
anyhow = "1"
approx = { default-features = false, version = "0.5" }
chrono = { default-features = false, version = "0.4" }
getrandom = { default-features = false, version = "0.3" }
glob = { default-features = false, version = "0.3" }
lazy_static = "1"
num = { default-features = false, version = "0.4" }
paste = "1"
rand = { default-features = false, version = "0.9" }
rand_distr = { default-features = false, version = "0.5" }
serde = { default-features = false, features = [ "derive" ], version = "1" }
serde_derive = { version = "1" }
serde_json = "1"
smart-default = "0.7"
strum = { default-features = false, features = [ "derive" ], version = "0.27" }
thiserror = { default-features = false, version = "2" }

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = "abort"
rpath = false

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
opt-level = "z"
overflow-checks = false
panic = "abort"
rpath = false
