[workspace.package]
authors = ["FL03 <jo3mccain@icloud.com>", "Scattered-Systems <jo3mccain@scattered-systems.com>"]
categories = []
description = "scsys is a collection of primitives and utilities for use throughout the ecosystem."
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["primitives", "scsys", "toolkit", "utilities"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys.git"
version = "0.2.3"

[workspace]
default-members = [
    "scsys",
]

exclude = []

members = [
    "actors",
    "core",
    "derive",
    "macros",
    "scsys",
]

resolver = "2"

[workspace.dependencies]
lazy_static = "1"
num = { default-features = false, version = "0.4" }
paste = "1"
smart-default = "0.7"
strum = { default-features = false, features = ["derive"], version = "0.26" }

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = "unwind"
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
panic = "abort"
rpath = false
opt-level = "z"
overflow-checks = false
