[workspace.package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys is a collection of primitives and utilities for use throughout the ecosystem."
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.2.2"

[workspace]
default-members = [
    "scsys",
]

exclude = []

members = [
    "actors",
    "core",
    "derive",
    "macros",
    "scsys", 
    "stores",
]

resolver = "2"

[workspace.dependencies]
paste = "1"
smart-default = "0.7"
strum = { features = ["derive"], version = "0.26" }

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = "unwind"
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
panic = "unwind"
rpath = false
opt-level = "z"
overflow-checks = false
