[workspace.package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.2.0"

[workspace.dependencies]
anyhow = "1"
chrono = "0.4"
glob = "0.3"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
smart-default = "0.6"
strum = { features = ["derive"], version = "0.24" }

[workspace]
default-members = [
    "scsys",
]

exclude = [
    "examples/*",
]

members = [
    "core",
    "derive",
    "macros",
    "scsys"
]

[profile.dev]
codegen-units = 256
debug = true
debug-assertions = true
incremental = true
lto = false
panic = "unwind"
rpath = false
opt-level = 0
overflow-checks = true

[profile.release]
codegen-units = 16
debug = false
debug-assertions = false
incremental = false
lto = false
panic = "unwind"
rpath = false
opt-level = "z"
overflow-checks = false
