[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-derive"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["derive", "macros", "scsys"]
license = "Apache-2.0"
name = "scsys-derive"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.41" # TODO: Update the package version

[lib]
proc-macro = true
test = false

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { features = ["full"], version = "1" }
serde = { features = ["derive"], version = "1"}
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]