[package]
authors = [
    "FL03 <jo3mccain@icloud.com> (https://github.com/FL03)",
    "Scattered-Systems (https://github.com/scattered-systems)"
]
categories = []
description = "Derive macros created for scsys"
edition = "2021"
homepage = "https://scattered-systems.github.io/scsys"
keywords = ["derive", "proc-macros"]
license = "MIT"
name = "scsys-derive"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.4" # TODO - Update cargo package version

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.43"
quote = "1.0.21"
syn = { features = ["full"], version = "1.0.99" }

[dev-dependencies.scsys]
path = "../scsys"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]