[package]
authors = [
    "FL03 <jo3mccain@icloud.com> (https://gitlab.com/FL03)",
    "Scattered-Systems (https://gitlab.com/scsys)"
]
categories = []
description = "Derive macros created for scsys"
edition = "2021"
homepage = "https://gitlab.com/scsys/lib/crates/scsys"
keywords = ["derive", "proc-macros"]
license = "MIT"
name = "scsys-derive"
readme = "README.md"
repository = "https://gitlab.com/scsys/lib/crates/scsys"
version = "0.1.20" # TODO - Update cargo package version

[lib]
proc-macro = true
test = false

[dependencies]
proc-macro2 = "1.0.46"
quote = "1.0.21"
syn = { features = ["full"], version = "1.0.102" }

[dev-dependencies.scsys]
path = "../scsys"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]