[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-actors"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []

full = [
    "serde",
    "tokio"
]

serde = [
    "dep:serde",
    "serde-ext",
    "scsys-core/serde",
]

serde-ext = [
    "dep:serde_json",
]

tokio = [
    "dep:tokio",
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[dependencies]
scsys-core = { path = "../core", version = "0.2.1" }

async-trait = "0.1"
config = "0.14"
futures = "0.3"
glob = "0.3"
serde = { optional = true, features = ["derive"], version = "1" }
serde_json = { optional = true, version = "1" }
smart-default.workspace = true
strum = { features = ["derive"], version = "0.26" }
tokio = { optional = true, features = ["sync"], version = "1" }


[dev-dependencies]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
