[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-actors"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["decanter/derive"]

wasi = []
wasm = ["decanter/wasm"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
chrono.workspace = true
decanter = { features = ["derive", "wasm"], version = "0.1.5" }
glob.workspace = true
serde.workspace = true
serde_json.workspace = true
smart-default.workspace = true
strum.workspace = true

[dependencies.scsys-core]
path = "../core"

[dev-dependencies]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
