[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-actors"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = []

serde = [
    "dep:serde",
    "serde-ext",
]

serde-ext = [
    "dep:serde_json",
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[dependencies]
async-trait = "0.1"
glob = "0.3"
serde = { optional = true, features = ["derive"], version = "1" }
serde_json = {optional = true, version = "1"}
smart-default.workspace = true
strum = { features = ["derive"], version = "0.26" }
tokio = { features = ["sync"], version = "1" }

[dependencies.scsys-core]
path = "../core"
version = "0.2.0"

[dev-dependencies]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
