[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-actors"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["core", "primitives", "scsys"]
license = "Apache-2.0"
name = "scsys-actors"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.41" # TODO: Update the package version

[features]
default = ["decanter/derive"]
wasm = ["decanter/wasm"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies]

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
chrono = "0.4.22"
config = "0.13.2"
decanter = { features = ["derive", "wasm"], version = "0.1.2" }
glob = "0.3.0"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
strum = { features = ["derive"], version = "0.24.1" }
url = "2.3.1"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
