[package]
name = "scsys-actors"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["decanter/derive"]
wasm = ["decanter/wasm"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies]

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
chrono = "0.4.22"
config = "0.13.2"
decanter = { features = ["derive", "wasm"], version = "0.1.2" }
glob = "0.3.0"
serde.workspace = true
serde_json.workspace = true
strum = { features = ["derive"], version = "0.24.1" }
url = "2.3.1"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
