[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-actors"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std",
]

full = [
    "default",
    "serde",
    "tokio"
]

serde = [
    "dep:serde",
    "serde-ext",
    "scsys-core/serde",
]

serde-ext = [
    "dep:serde_json",
]

std = [
    "scsys-core/std",
]

tokio = [
    "dep:tokio",
    "tokio-ext",
]

tokio-ext = [
    "tokio/sync",
]

wasi = [
    "scsys-core/wasi"
]

wasm = [
    "scsys-core/wasm"
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[dependencies]
async-trait = "0.1"
config = "0.14"
futures = "0.3"
glob = "0.3"
paste.workspace = true
serde = { optional = true, features = ["derive"], version = "1" }
serde_json = { optional = true, version = "1" }
smart-default.workspace = true
strum.workspace = true
tokio = { optional = true, version = "1" }

[dependencies.scsys-core]
path = "../core"
version = "0.2.1"
# version = "0.2.1-nightly"

[dev-dependencies]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
