[package]
authors.workspace = true
categories = []
description = "scsys-actors"
edition.workspace = true
homepage.workspace = true
keywords = []
license.workspace = true
name = "scsys-actors"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["decanter/derive"]
wasm = ["decanter/wasm"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
chrono.workspace = true
config = "0.13"
decanter = { features = ["derive", "wasm"], version = "0.1.3" }
glob.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true

[dev-dependencies]

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
