version: 2.1

jobs:
  build:
    docker:
      - image: rust:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test --all --all-features --color always -v"