[package]
build = "build.rs"
description = "core primitives and utilities for the scsys ecosystem"
name = "scsys-core"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = [ "--cfg", "docsrs" ]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[lib]
crate-type = [
  "cdylib",
  "rlib",
  "staticlib"
]
bench = false
doc = true
doctest = false
test = true

[dependencies]
# error-handling
anyhow = { optional = true, workspace = true }
thiserror = { workspace = true }
# mathematics
num-traits = { workspace = true }
# randomization
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
uuid = { optional = true, workspace = true }
# serialization
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# macros & utilities
paste = { workspace = true }
smart-default = { workspace = true }
strum = { workspace = true }
# time
chrono = { optional = true, workspace = true }
time = { optional = true, workspace = true }
# tracing
tracing = { optional = true, workspace = true }
# wasm
wasm-bindgen = { optional = true, workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
approx = { workspace = true }

[features]
default = [ "std" ]

full = [
  "default",
  "anyhow",
  "chrono",
  "json",
  "rand",
  "serde",
  "time",
  "tracing",
]

nightly = []

# ************* [FF:Features] *************

json = [
  "alloc",
  "serde",
  "serde_json",
]

time = [
  "std",
  "time-0"
]

# ************* [FF:Environments] *************

std = [
  "alloc",
  "anyhow?/std",
  "num-traits/std",
  "rand?/std",
  "rand?/std_rng",
  "serde?/std",
  "strum/std",
  "thiserror/std",
  "time?/std",
  "tracing?/std",
  "uuid?/std",
]

wasi = [
  "alloc"
]

wasm = [
  "alloc",
  "wasm-bindgen",
  "getrandom?/wasm_js",
  "uuid?/js",
]

# ************* [FF:Dependencies] *************

anyhow = ["dep:anyhow"]

alloc = [
  "chrono?/alloc",
  "serde?/alloc",
  "serde_json?/alloc",
  "time?/alloc",
]

chrono = [
  "dep:chrono",
  "chrono?/clock",
]

rand = [
  "dep:rand",
  "dep:rand_distr",
  "rng",
]

rng = [
  "dep:getrandom",
  "rand?/small_rng",
  "rand?/thread_rng",
  "uuid?/rng",
  "uuid?/v4"
]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "chrono?/serde",
  "rand?/serde",
  "uuid?/serde",
  "time?/serde",
]

serde_json = ["dep:serde_json"]

time-0 = ["dep:time"]

tracing = ["dep:tracing"]

uuid = [
  "dep:uuid",
  "uuid?/v3"
]

wasm-bindgen = [
  "dep:wasm-bindgen",
  "chrono?/wasmbind",
  "time?/wasm-bindgen",
]

# ************* [Unit Tests] *************
[[test]]
name = "default"

[[test]]
name = "time"
required-features = ["std", "time"]
