[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://scattered-systems.github.io/scsys/"
keywords = ["core", "scsys"]
license = "MIT"
name = "scsys-core"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.5" # TODO: Update the package version


[lib]
test = true

[build-dependencies]

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
chrono = "0.4.22"
config = "0.13.2"
futures = "0.3.24"
glob = "0.3.0"
log = "0.4.17"
rand = "0.8.5"
serde = { features = ["derive"], version = "1.0.144" }
serde_json = "1.0.85"
strum = {features = ["derive"], version = "0.24.1" }
strum_macros = "0.24.1"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]