[package]
build = "build.rs"
name = "scsys-core"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = [ "cdylib", "rlib" ]
doctest = true
test = true

[features]
default = [ "std" ]

full = [ 
    "default", 
    "rand", 
    "serde", 
    "time" 
]

# ******* [FF] Dependencies *******
anyhow = ["dep:anyhow"]

alloc = [ 
    "num/alloc", 
    "serde?/alloc"
]

chrono = [ 
    "dep:chrono", 
    "chrono?/clock",
]

json = [ 
    "dep:serde_json", 
    "alloc", 
    "serde"
]

rand = [
    "dep:rand",
    "dep:rand_distr",
    "num/rand",
    "rng",
]

rng = [
    "dep:getrandom",
    "rand?/small_rng",
    "rand?/thread_rng",
    "uuid?/rng",
    "uuid?/v4"
]

serde = [ 
    "dep:serde", 
    "dep:serde_derive", 
    "num/serde", 
    "rand?/serde", 
    "uuid?/serde" 
]

time = [ "chrono", "dep:time" ]

uuid = ["dep:uuid"]

# ******* [FF] Environment *******
std = [
    "alloc",
    "anyhow?/std",
    "num/std",
    "rand?/std",
    "rand?/std_rng",
    "serde?/std",
    "strum/std",
    "thiserror/std",
    "uuid?/std",
]

wasi = [  ]

wasm = [ "getrandom?/wasm_js" ]

[dependencies]
glob = { workspace = true }
num = { workspace = true }
paste = { workspace = true }

serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
smart-default = { workspace = true }
strum = { workspace = true }
# errors
anyhow = { optional = true, workspace = true }
thiserror = { workspace = true }
# randomization
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
uuid = { optional = true, workspace = true }
# time
chrono = { optional = true, workspace = true }
time = { optional = true, workspace = true }




[dev-dependencies]
approx = { version = "0.5" }

[package.metadata.docs.rs]
rustc-args = [ "--cfg", "docsrs" ]

# ********* tests *********
[[test]]
name = "default"

[[test]]
name = "state"
required-features = [ "std" ]

[[test]]
name = "time"
required-features = [ "std", "time" ]

