[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-core"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["core", "primitives", "scsys"]
license = "MIT"
name = "scsys-core"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.22" # TODO: Update the package version

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
anyhow = "1.0.65"
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
chrono = "0.4.22"
config = "0.13.2"
futures = "0.3.24"
glob = "0.3.0"
hex = "0.4.3"
log = "0.4.17"
nom = "7.1.1"
rand = { features = ["serde1"], version = "0.8.5" }
ring = "0.16.20"
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
strum = { features = ["derive"], version = "0.24.1" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
url = "2.3.1"

[dev-dependencies]
vrf = "0.2.4"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]
