[package]
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-core"
readme.workspace = true
repository.workspace = true
version.workspace = true


[features]
default = [
    "std"
]

full = [
    "default",
    "rand",
    "serde",
]

# ******* [FF] Dependencies *******
alloc = [
    "num/alloc",
    "rand?/alloc",
    "serde?/alloc",
]

chrono = [
    "dep:chrono"
]

rand = [
    "dep:rand",
    "num/rand",
]

serde = [
    "dep:serde",
    "serde-ext",
]

serde-ext = [
    "num/serde",
    "rand?/serde1",
]

# ******* [FF] Environment *******
std = [
    "alloc",
    "num/std",
    "rand?/std",
    "rand?/std_rng",
    "serde?/std",
    "strum/std",
]

wasi = []

wasm = [
    "getrandom/js",
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[test]]
name = "errors"
required-features = ["std"]

[build-dependencies]

[dev-dependencies]
anyhow = "1"
serde_json = "1"

[dependencies]
glob = "0.3"
num.workspace = true
smart-default.workspace = true
strum.workspace = true

[dependencies.chrono]
optional = true
version = "0.4"

[dependencies.rand]
default-features = false
optional = true
version = "0.8"

[dependencies.serde]
default-features = false
features = ["derive"]
optional = true
version = "1"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown.dependencies]
getrandom = "0.2"

[target.wasm32-wasi]
