[package]
build = "build.rs"
name = "scsys-core"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true


[features]
default = ["std"]

full = ["default", "chrono", "rand", "serde"]

# ******* [FF] Dependencies *******
alloc = ["num/alloc", "rand?/alloc", "serde?/alloc"]

chrono = ["dep:chrono"]

rand = ["dep:rand", "num/rand"]

serde = ["dep:serde", "serde?/derive", "num/serde", "rand?/serde1"]

# ******* [FF] Environment *******
std = [
    "alloc",
    "num/std",
    "rand?/std",
    "rand?/std_rng",
    "serde?/std",
    "strum/std",
    "thiserror/std",
]

wasi = []

wasm = ["getrandom/js"]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[test]]
name = "errors"
required-features = ["std"]


[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true

[dependencies]
num.workspace = true
smart-default.workspace = true
strum.workspace = true
thiserror.workspace = true

glob = "0.3"
paste = "1"

chrono = { optional = true, version = "0.3" }
rand = { default-features = false, optional = true, version = "0.8" }
serde = { default-features = false, optional = true, version = "0.8" }


[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown.dependencies]
getrandom = "0.2"

[target.wasm32-wasi]
