[package]
build = "build.rs"
name = "scsys-core"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = [ "cdylib", "rlib", "staticlib" ]
doctest = true
test = true

[features]
default = [ "std" ]

full = [ "chrono", "default", "rand", "serde" ]

# ******* [FF] Dependencies *******
alloc = [ "num/alloc", "rand?/alloc", "serde?/alloc" ]

chrono = [ "dep:chrono" ]

rand = [ "dep:rand", "num/rand" ]

serde = [ "dep:serde", "dep:serde_derive", "num/serde", "rand?/serde", "serde?/derive" ]

# ******* [FF] Environment *******
std = [
    "alloc",
    "num/std",
    "rand?/std",
    "rand?/std_rng",
    "serde?/std",
    "strum/std",
    "thiserror/std",
]

wasi = [  ]

wasm = [ "getrandom/wasm_js" ]

[[test]]
name = "errors"
required-features = [ "std" ]

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }

[dependencies]
# shared
num = { workspace = true }
paste = { workspace = true }
rand = { optional = true, workspace = true }
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
smart-default = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }

# feature=specific
chrono = { optional = true, version = "0.4" }
glob = "0.3"

[package.metadata.docs.rs]
rustc-args = [ "--cfg", "docsrs" ]

[target.wasm32-unknown-unknown.dependencies]
getrandom = "0.3"

[target.wasm32-wasi]
