[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-core"
readme.workspace = true
repository.workspace = true
version.workspace = true


[features]
default = []

serde = [
    "dep:serde",
    "serde-ext",
]

serde-ext = [
    "dep:serde_json",
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[dependencies]
anyhow.workspace = true
bson = { features = ["chrono-0_4", "uuid-0_8"], version = "2.9" }
chrono = "0.4"
config = "0.14"
glob = "0.3"
predicates = "3"
rand = "0.8"
serde = { optional = true, features = ["derive"], version = "1" }
serde_json = {optional = true, version = "1"}
smart-default.workspace = true
strum = { features = ["derive"], version = "0.26" }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown.dependencies]
getrandom = { features = ["js"], version = "0.2" }

[target.wasm32-wasi]
