[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "scsys-core"
readme.workspace = true
repository.workspace = true
version.workspace = true


[features]
default = []

wasm = [
    "getrandom/js"
]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
anyhow = "1"
bson = { features = ["chrono-0_4", "uuid-0_8"], version = "2.4" }
chrono = "0.4"
config = "0.13"
getrandom = { features = ["js"], version = "0.2" }
glob = "0.3"
rand = "0.8.5"
serde.workspace = true
serde_json.workspace = true
smart-default.workspace = true
strum.workspace = true
url = "2.3"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
