[package]
build = "build.rs"
name = "scsys-util"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[lib]
bench = false

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }

[dependencies]
# math
num-traits = { workspace = true }
# random
getrandom = { optional = true, workspace = true }
rand = { optional = true, workspace = true }
rand_distr = { optional = true, workspace = true }
# serialization
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# macros & utilities
strum = { workspace = true }
# tracing
tracing = { optional = true, workspace = true }
# wasm
wasm-bindgen = { optional = true, workspace = true }

[features]
default = [
  "std",
  "fs",
]

full = [
  "default",
  "json",
  "rand",
  "serde",
  "tracing",
]



# ************* [FF:Features] *************
fs = [
  "std",
]

# ********* [FF] Standard Library *********
alloc = [
  "serde?/alloc",
  "serde_json?/alloc",
]

std = [
  "alloc",
  "num-traits/std",
  "rand?/default",
  "rand_distr?/std",
  "serde?/std",
  "strum/std",
  "tracing?/std",
  "wasm-bindgen?/std",
]

# ********* [FF] Targets *********
nightly = []

wasi = [
  "std"
]

wasm = [
  "std",
  "wasm_bindgen",
  "getrandom?/wasm_js",
]

# ************* [FF:Dependencies] *************

json = [
  "alloc",
  "serde",
  "serde_json",
]

rand = [
  "dep:rand",
  "dep:rand_distr",
  "rng",
]

rng = [
  "dep:getrandom",
  "getrandom?/sys_rng",
  "rand?/sys_rng",
]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "serde?/derive",
  "rand?/serde",
  "rand_distr?/serde",
  "wasm-bindgen?/serde-serialize",
]

serde_json = [
  "dep:serde_json",
  "wasm-bindgen?/serde_json",
]

tracing = ["dep:tracing"]

wasm_bindgen = ["dep:wasm-bindgen"]

# ************* [Unit Tests] *************
[[test]]
name = "casing"
required-features = ["alloc"]
