.cargo_build_template: &cargo_build
  stage: build
  script:
    - cargo build --release --workspace --jobs 1

.cargo_deploy_template: &cargo_publish
  stage: publish
  before_script:
    - cargo login $CARGO_REGISTRY_TOKEN
  script:
    - cargo publish -p scsys-core -v --jobs 1
    - cargo publish -p scsys-derive -v --jobs 1
    - cargo publish -p scsys-macros -v --jobs 1
  after_script:
    - cargo publish --all-features -p scsys  -v --jobs 1

.cargo_test_template: &cargo_test
  stage: test
  script:
    - cargo test --all-features --release --jobs 1

stages:
  - build
  - publish
  - test

variables:
  CARGO_REGISTRY_TOKEN: $CARGO_REGISTRY_TOKEN

stable:rust:
  image: rustdocker/rust:stable
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_build
  <<: *cargo_test
  <<: *cargo_publish

nightly:rust:
  allow_failure: true
  image: rustdocker/rust:nightly
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  <<: *cargo_build
  <<: *cargo_test
  <<: *cargo_publish