variables:
  CARGO_REGISTRY_TOKEN: $CARGO_REGISTRY_TOKEN

stages:
  - deploy
  - testing

cargo:test:
  image: rustdocker/rust:stable
  stage: testing
  script:
    - cargo test --all-features --release --verbose --jobs 1
    - cargo clippy

cargo:deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
  before_script:
    - cargo login $CARGO_REGISTRY_TOKEN
    - cargo fmt --all
  script:
    - cargo publish -p scsys-derive --verbose
    - cargo publish -p scsys-macros --verbose
    - cargo publish --all-features --package scsys  -v