[package]
build = "build.rs"
description = "common configuration routines and schemas used throughout the ecosystem"
name = "scsys-config"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
bench = false
doc = true
doctest = true
test = true

[dependencies]
config = { default-features = false, optional = true, version = "0.15" }
# error handling
anyhow = { features = ["std"], workspace = true }
# data & serialization
serde = { features = ["derive", "std"], optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { features = ["std"], optional = true, workspace = true }
# macros
smart-default = { workspace = true }
strum = { features = ["derive", "std"], workspace = true }
# logging
tracing = { optional = true, workspace = true }
tracing-subscriber = { optional = true, workspace = true }

[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = [ "--cfg", "docsrs" ]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[features]
default = [
    "config",
    "async",
    "convert-case",
    "ini",
    "json",
    "json5",
    "ron",
    "toml",
    "yaml",
]

full = [
    "default",
    "tracing",
    "tracing-subscriber",
]

# ************* [FF:Dependencies] *************
async = [
    "config?/async",
]

config = ["dep:config"]

serde = [
    "dep:serde",
    "dep:serde_derive",
    "tracing-subscriber?/serde",
]

serde_json = [
    "dep:serde_json", 
    "config?/serde_json",
    "serde",
]

tracing = ["dep:tracing"]

tracing-subscriber = [
    "dep:tracing-subscriber",
    "tracing",
]
# ************* [FF:config] *************
convert-case = ["config?/convert-case"]

ini = ["config?/ini"]

json = [
    "serde_json",
    "config?/json",
]

json5 = [ "config?/json5" ]

ron = ["config?/ron"]

toml = ["config?/toml"]

yaml = ["config?/yaml"]

# ************* [Unit Tests] *************
[[test]]
name = "default"