[package]
name = "scsys-util"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std"
]

full = [
    "default",
    "rand",
    "serde",
]

# ******* [FF] Dependencies *******
alloc = [
    "num/alloc",
    "rand?/alloc",
    "serde?/alloc",
]

rand = [
    "dep:rand",
    "num/rand",
]

serde = [
    "dep:serde",
    "num/serde",
    "serde?/derive",
    "rand?/serde1",
]

# ******* [FF] Environment *******
std = [
    "alloc",
    "num/std",
    "rand?/std",
    "rand?/std_rng",
    "serde?/std",
    "strum/std",
]

wasi = []

wasm = [
    "getrandom/js",
]

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[test]]
name = "casing"
required-features = ["alloc"]

[build-dependencies]

[dev-dependencies]
anyhow = "1"
serde_json = "1"

[dependencies]
# shared
num.workspace = true
strum.workspace = true

# optional 
rand = { default-features = false, optional = true, version = "0.9" }
serde = { default-features = false, optional = true, version = "1" }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[target.'cfg(target_family = "wasm32")'.dependencies]
getrandom = "0.2"

[target.wasm32-wasi]
