[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-gen"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["scsys"]
license = "Apache-2.0"
name = "scsys-gen"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.41" # TODO: Update the package version

[features]
default = []

wasm = [ 
    "wasm-ext"
]
wasm-ext = [
    "getrandom/js"
]

[lib]
crate-type = ["cdylib", "rlib"]
test = true


[dependencies]
getrandom = { features = ["js"], version = "0.2" }
rand = "0.8.5"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
