[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-gen"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["scsys"]
license = "MIT"
name = "scsys-gen"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.28" # TODO: Update the package version

[features]
default = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies.scsys-core]
path = "../core"

[dependencies]

serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
strum = { features = ["derive"], version = "0.24.1" }


[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
