[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-gen"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["scsys"]
license = "Apache-2.0"
name = "scsys-gen"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.34" # TODO: Update the package version

[features]
default = ["wasm"]
full = ["wasm", "wasm-ext"]

wasm = []
wasm-ext = [
    "rand"
]

rand = ["getrandom/js"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dev-dependencies.scsys-core]
path = "../core"

[dependencies]
chrono = "0.4.22"
getrandom = { features = ["js"], version = "0.2" }
rand = "0.8.5"
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
strum = { features = ["derive"], version = "0.24.1" }


[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
