[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-macros"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["macros", "scsys"]
license = "Apache-2.0"
name = "scsys-macros"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.34" # TODO: Update the package version

[lib]
crate-type = ["cdylib", "rlib"]
test = false

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
proc-macro2 = "1.0.46"
quote = "1.0.21"
rand = "0.8.5"
syn = { features = ["full"], version = "1.0.102" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]