[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys-crypto"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["crypto", "scsys"]
license = "MIT"
name = "scsys-crypto"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.28" # TODO: Update the package version

[features]
default = ["core", "extras", "wasm"]
full = ["core", "extras", "wasm"]

core = []
extras = [
    "getrandom/std"
]

wasm = [
    "wasm-ext"
]

wasm-ext = [
    "getrandom/js",
    "ring/wasm32_c"
]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
blake3 = "1.3.1"
ed25519 = { features = ["pkcs8", "serde_bytes"], version = "1.5.2" }
generic-array = "0.14.6"
getrandom = { features = ["js"], optional = true, version = "0.2" }
hex = "0.4.3"
hex-literal = "0.3.4"
itertools = "0.10.5"
rand = "0.8.5"
ring = { features = ["wasm32_c"], version = "0.16.20" }
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
typenum = "1.15.0"

[dev-dependencies]
vrf = "0.2.4"