name: clippy

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

on:
  pull_request:
    branches: [ main, master, $default-branch ]
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths:
      - ".github/workflows/cargo-clippy.yml"
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  push:
    branches: [ main, master, $default-branch ]
    tags:
      - v*.*.*
      - "*-nightly"
  release:
    types: [ created, edited ]
  repository_dispatch:
    types: [ clippy, cargo-clippy ]
  workflow_dispatch:

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ full ]
        toolchain: [ stable ]
    permissions:
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      contents: read
      security-events: write
      statuses: write
    steps:
      - 
        name: Checkout the source code
        uses: actions/checkout@v5
      - 
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          components: clippy,rustfmt
          override: true
          toolchain: ${{ matrix.toolchain }}
      - 
        name: Setup cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.16.2
      -
        name: Install clippy-sarif and sarif-fmt
        run: cargo binstall -qy --force clippy-sarif sarif-fmt
      -
        name: Analyze the code with clippy
        run:
          cargo clippy
          --features ${{ matrix.features }}
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      -
        name: Upload the analysis
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
