name: Clippy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ nightly*,  v*.*.* ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ clippy ]
  schedule:
    - cron: "30 21 * * 0" # Every Sunday at 9:30am UTC
  workflow_dispatch:

permissions:
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
  contents: read
  security-events: write

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup (rust)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: setup (clippy)
        run: cargo install clippy-sarif sarif-fmt
      - name: analyze
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload analysis
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
