name: crates.io

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  core:
    env:
      PACKAGE: ${{ github.event.repository.name }}-${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ core ]
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: publish (${{ matrix.package }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE }}
  features:
    env:
      PACKAGE: ${{ github.event.repository.name }}-${{ matrix.package }}
    needs: core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ actors, derive, macros, utils ]
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: publish (${{ matrix.package }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE }}
  sdk:
    env:
      PACKAGE: ${{ github.event.repository.name }}
    needs: [ core, features ]
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: publish
        run: cargo publish --all-features -v -p ${{ env.PACKAGE }}
