name: Crates

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

on:
  push:
    tags: [ "nightly*",  "v*.*.*" ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ publish ]
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  base:
    name: Publish (core)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ core ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    name: Publish (features)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ actors, core, derive, generate, macros ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}
    name: Publish (sdk)
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
