name: crates.io

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  core:
    name: Publish (core)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: publish
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}-core --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    name: Publish (features)
    needs: core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ actors, derive, macros, ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.package }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  sdk:
    name: Publish (sdk)
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: publish
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
