name: crates-io

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: scsys=debug,info

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  packages: write

jobs:
  deps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        feature: [ "util", "core", "derive", "macros" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - 
        name: rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - 
        name: cache
        uses: Swatinem/rust-cache@v2
      - 
        name: publish (${{ matrix.feature }})
        run: cargo publish --all-features -v -p scsys-${{ matrix.feature }}
  root:
    needs: [deps]
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - 
        name: cache
        uses: Swatinem/rust-cache@v2
      - 
        name: publish
        run: cargo publish --all-features -v -p scsys
