name: crates.io

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ created ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  crates-io:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: rustup
        run: |
          rustup update
      - 
        name: publish
        run: |
          cargo publish --all-features -v -p scsys-core
          cargo publish --all-features -v -p scsys-actors
          cargo publish --all-features -v -p scsys-derive
          cargo publish --all-features -v -p scsys-macros
          cargo publish --all-features -v -p scsys-utils
          cargo publish --all-features -v -p scsys
      - 
        id: rust-cache
        name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
