name: release

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ release ]
  workflow_dispatch:
    inputs:
      draft:
        default: false
        description: 'Create a draft release'
        required: true
        type: boolean
      prerelease:
        default: false
        description: 'Create a prerelease'
        required: true
        type: boolean

permissions:
  actions: read 
  contents: write
  discussions: write

jobs:
  publish:
    environment: 
      name: crates-io
      url: https://crates.io/crates/${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Publish to crates.io
        uses: peter-evans/repository-dispatch@v3 
        with:
          event-type: crates-io          
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          token: ${{ github.token }}
  release:
    needs: publish    
    env:
      IS_PRERELEASE: ${{ github.event.inputs.prerelease || false }}
      IS_DRAFT: ${{ github.event.inputs.draft || false }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Create release
        uses: softprops/action-gh-release@v1
        with:
          append_body: false
          draft: ${{ env.IS_DRAFT }}
          prerelease: ${{ env.IS_PRERELEASE }}
          tag_name: ${{ github.event.release.tag_name }}
          body: |
            ${{ github.event.release.body }}
          files: |
            target/release/scsys
