name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches-ignore: [ "dev*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  push:
    branches-ignore: [ "dev*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain:
          - stable
          - nightly
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build -F full --release -v --workspace
      - name: Test
        run: cargo test --all -F full --release -v
  features:
    if: ${{ github.event.inputs.publish }}
    name: Publish (features)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - scsys-actors
          - scsys-core
          - scsys-derive
          - scsys-macros
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{matrix.package}})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish (sdk)
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (scsys)
        run: cargo publish --all-features -v -p scsys --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
