name: Rust

on:
  pull_request:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo login ${CARGO_REGISTRY_TOKEN}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose --workspace
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features --release --verbose