name: Rust

on:
  pull_request:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo login ${CARGO_REGISTRY_TOKEN}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose --workspace
  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --all-features --release --verbose
  features:
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: core
      run: cargo publish --all-features -p scsys-core -v --token $CARGO_REGISTRY_TOKEN
    - name: crypto
      run: cargo publish --all-features -p scsys-crypto -v --token $CARGO_REGISTRY_TOKEN
    - name: derive
      run: cargo publish --all-features -p scsys-derive -v --token $CARGO_REGISTRY_TOKEN
    - name: macros
      run: cargo publish --all-features -p scsys-macros -v --token $CARGO_REGISTRY_TOKEN
  publish:
    needs: [ features, login, test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: core
      run: cargo publish --all-features -p scsys -v --token ${CARGO_REGISTRY_TOKEN}
