name: Rust

on:
  push:
    branches:
      - latest
    tags:
      - v*.*.*
  pull_request:
    branches:
      - latest
    tags:
      - v*.*.*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test (workspace)
        run: cargo test --all-features --color always --verbose --workspace
  core:
    env:
      CARGO_PKG_NAME: scsys-core
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  derive:
    env:
      CARGO_PKG_NAME: scsys-derive
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  macros:
    env:
      CARGO_PKG_NAME: scsys-macros
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  crate:
    env:
      CARGO_PKG_NAME: scsys
    needs: [ core, derive, login, macros, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features