name: rust

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUST_LOG: scsys=debug,info

on:
  pull_request:
    branches: [ main, master ]
  push:
    tags: [ v*.*.*, "*-nightly" ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ rust ]
  workflow_dispatch:

permissions: write-all

jobs:
  workspace:
    strategy:
      fail-fast: false
      matrix:
        os:  [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: setup cache
        uses: Swatinem/rust-cache@v2
      - 
        name: setup rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          cache-workspaces: true
      - 
        name: build (workspace)
        run: cargo build --locked --release --workspace --all-features
      - 
        name: test (workspace)
        run: cargo test --locked --release --workspace --all-features
      - 
        name: benchmark
        run: cargo bench -v --workspace --features full
