name: Rust

on:
  push:
    branches:
      - master
    tags:
      - latest
  pull_request:
    branches:
      - master

jobs:
  crate:
    env:
      CARGO_PKG_NAME: scsys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Test
        run: cargo test --all-features --color always --package $CARGO_PKG_NAME --verbose
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}