name: Rust

on:
  push:
    tags:
      - v*.*.*
  pull_request:
    tags:
      - v*.*.*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    env:
      CARGO_PKG_NAME: scsys-derive
    needs: [ login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test (macros)
        run: cargo test --color always --package scsys-macros --verbose
      - name: Publish (derive)
        run: cargo publish --package scsys-derive --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish (macros)
        run: cargo publish --package scsys-macros --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  crate:
    env:
      CARGO_PKG_NAME: scsys
    needs: [ features, login ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test --all-features --color always --verbose
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --all-features