name: Rust

on:
  push:
    branches:
      - master
    tags:
      - latest
      - v*.*.*
  pull_request:
    branches:
      - master
    tags:
      - latest
      - v*.*.*

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test (scsys)
        run: cargo test --all-features --color always --package scsys --verbose
  crate:
    env:
      CARGO_PKG_NAME: scsys
    needs: [ login, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: cargo publish --package $CARGO_PKG_NAME --all-features --token ${{ secrets.CARGO_REGISTRY_TOKEN }}