name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches-ignore: [ "beta*", "dev*", "next*" ]
  push:
    branches-ignore: [ "beta*", "dev*", "next*" ]
    tags: [ "nightly*",  "v*.*.*" ]
  release:
  repository_dispatch:
    types: [ "rust" ]
  schedule:
    - cron: "30 21 * * *" # 9:30pm UTC
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        toolchain: [ nightly ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup (langspace)
        run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build -F full --release -v --workspace
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: cargo test --all -F full --release -v
      - name: Bench
        if: matrix.toolchain == 'nightly'
        run: cargo bench --all -F full -v
