name: rust

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

on:
  pull_request:
    branches: [ main, master, $default-branch ]
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths:
      - ".github/workflows/rust.yml"
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  push:
    branches: [ main, master, $default-branch ]
    tags: [ latest, v*.*.*, "*-nightly" ]
  repository_dispatch:
    types: [ rust ]
  workflow_dispatch:
    inputs:
      benchmark:
        default: true
        description: 'Run benchmarks'
        required: true
        type: boolean
      nightly:
        default: false
        description: 'Run tests with the nightly toolchain?'
        required: true
        type: boolean



jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-gnu ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          target: ${{ matrix.target }}
      -
        name: Build the workspace
        run: cargo build -r --locked --workspace --features full --target ${{ matrix.target }}
  benchmark:
    if: github.event.inputs.benchmark || github.event_name == 'repository_dispatch' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.benchmark.outputs.digest }}
      id: ${{ steps.benchmark.outputs.id }}
      url: ${{ steps.benchmark.outputs.url }}
    permissions:
      actions: read
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      -
        name: Benchmark the workspace
        id: benchmark
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: cargo-bench
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          token: ${{ github.token }}
  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        features:  [ default, full ]
        target: [ x86_64-unknown-linux-gnu ]
        toolchain: [ stable ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      -
        name: cargo test (${{ matrix.features }})
        run: |
          if [[ "${{ matrix.features }}" == "all" ]]; then
            cargo test -r --locked --workspace --target ${{ matrix.target }} --all-features
          elif [[ "${{ matrix.features }}" == "default" ]]; then
            cargo test -r --locked --workspace --target ${{ matrix.target }}
          else
            cargo test -r --locked --workspace --target ${{ matrix.target }} --features ${{ matrix.features }}
          fi
  test_nightly:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        features:  [ all, no_std, "alloc,nightly" ]
        toolchain: [ nightly ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      -
        name: Test (all)
        if: matrix.features == 'all'
        run: cargo test -r --locked --workspace --all-features
      -
        name: Test (no_std)
        if: matrix.features == 'no_std'
        continue-on-error: true
        run: cargo test -r --locked --workspace --no-default-features
        env:
          RUSTFLAGS: "-C panic=abort -Z panic_abort_tests"
      -
        name: Test (${{ matrix.features }})
        if: matrix.features != 'all' && matrix.features != 'no_std'
        continue-on-error: true
        run: cargo test -r --locked --workspace --no-default-features --features ${{ matrix.features }}
        env:
          RUSTFLAGS: "-C panic=abort -Z panic_abort_tests"
