name: rust

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always

on:
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]
  repository_dispatch:
    types: [ rust ]
  workflow_dispatch:

permissions: write-all

jobs:
  workspace:
    strategy:
      fail-fast: false
      matrix:
        os:  [ ubuntu-latest ] # [ ubuntu-latest, macos-latest, windows-latest ]
        target: [ x86_64-unknown-linux-gnu, ]
        toolchain: [ stable, nightly, ]
    runs-on: ${{ matrix.os }}
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      - 
        name: setup rustup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: true
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
      - 
        name: cache
        uses: Swatinem/rust-cache@v2
      - 
        name: build
        run: cargo build -r -v --workspace --features full --target ${{ matrix.target }}
      - 
        name: test
        run: cargo test -r -v --workspace --features full --target ${{ matrix.target }}
      - 
        name: bench
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: cargo bench -v --workspace --features full
