name: sandbox

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

on:
  repository_dispatch:
    types: [ sandbox ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  packages: write

jobs:
  deps:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        prefix: [ scsys ]
        feature: [ traits, util, core, cnf, derive, macros ]
        include:
          - prefix: scsys
            feature: traits
          - prefix: scsys
            feature: util
          - prefix: scsys
            feature: core
          - prefix: scsys
            feature: cnf
          - prefix: scsys
            feature: derive
          - prefix: scsys
            feature: macros
          - prefix: scsys
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.prefix }}-${{ matrix.feature }}