[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://gitlab.com/scsys/lib/crates/scsys/-/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://gitlab.com/scsys/lib/crates/scsys"
version = "0.1.19" # TODO: Update the package version

[features]
default = ["core"]
full = ["core", "derive", "macros", "extras"]

core = ["scsys-core"]
derive = ["scsys-derive"]
macros = ["scsys-macros"]

extras = ["anyhow", "bson", "chrono", "config", "rand"]
anyhow = ["anyhow/default"]
bson = ["bson/default", "bson/chrono-0_4", "bson/serde_with", "bson/uuid-0_8"]
chrono = ["chrono/default"]
config = ["config/default"]
rand = ["rand/default"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
anyhow = { features = ["default"], version = "1.0.65" }
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], optional = true, version = "2.4.0" }
chrono = { optional = true, version = "0.4.22" }
config = { optional = true, version = "0.13.2" }
rand = { optional = true, version = "0.8.5" }

[dependencies.scsys-core]
optional = true
path = "../core"
version = "0.1.7"

[dependencies.scsys-derive]
optional = true
path = "../derive"
version = "0.1.9" # TODO: Update feature versioning

[dependencies.scsys-macros]
optional = true
path = "../macros"
version = "0.1.9" # TODO: Update feature versioning

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
