[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://scattered-systems.github.io/scsys/"
keywords = ["blockchain", "primitives", "scsys"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://gitlab.com/scsys/scsys"
version = "0.1.13" # TODO: Update the package version

[features]
default = ["core"]
full = ["core", "derive", "macros"]

core = ["scsys-core"]
derive = ["scsys-derive"]
macros = ["scsys-macros"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies.scsys-core]
optional = true
path = "../core"
version = "0.1.4" # TODO: Update feature versioning

[dependencies.scsys-derive]
optional = true
path = "../derive"
version = "0.1.3" # TODO: Update feature versioning

[dependencies.scsys-macros]
optional = true
path = "../macros"
version = "0.1.3" # TODO: Update feature versioning

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]