[package]
build = "build.rs"
name = "scsys"

authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
bench = true
crate-type = [ "cdylib", "rlib" ]
doctest = true
test = true

[features]
default = [
    "std",
    "utils",
]

full = [
    "actors",
    "default",
    "derive",
    "json",
    "macros",
    "rand",
    "serde",
    "time",
    "tokio",
]

# ********* [FF] Features *********

actors = [
    "dep:scsys-actors",
]

derive = [
    "dep:scsys-derive",
]

macros = [
    "dep:scsys-macros",
]

utils = [
    "dep:scsys-util",
]

# ********* [FF] Dependencies *********
alloc = [
    "scsys-actors?/alloc",
    "scsys-core/alloc",
    "scsys-util?/alloc",
]

json = [
    "scsys-core/json",
]

rand = [
    "scsys-core/rand",
]

serde = [
    "scsys-actors?/serde",
    "scsys-core/serde",
    "scsys-util?/serde",
]

time = [
    "scsys-core/time",
]

tokio = [
    "scsys-actors?/tokio",
]

# ********* [FF] Environments *********
std = [
    "scsys-actors?/std",
    "scsys-core/std",
    "scsys-util?/std",
]

wasi = [
    "scsys-actors?/wasi",
    "scsys-core/wasi",
]

wasm = [
    "scsys-actors?/wasm",
    "scsys-core/wasm",
]

[dependencies]
scsys-core = { default-features = false, path = "../core", version = "0.2.4" }

scsys-actors = { default-features = false, optional = true, path = "../actors", version = "0.2.4" }
scsys-derive = { default-features = false, optional = true, path = "../derive", version = "0.2.4" }
scsys-macros = { default-features = false, optional = true, path = "../macros", version = "0.2.4" }
scsys-util = { default-features = false, optional = true, path = "../utils", version = "0.2.4" }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustc-args = [ "--cfg", "docsrs" ]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

# ********* examples *********
[[example]]
name = "derive"
required-features = [ "derive", "serde" ]

# ********* test *********
[[test]]
name = "derive"
required-features = [ "derive" ]
