[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "Apache-2.0"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.41" # TODO: Update the package version

[features]
default = [
    "actors",
    "core",
    "derive",
    "gen",
    "macros"
]
full = [
    "actors",
    "core",
    "gen",
    "derive", 
    "macros", 
    "extras"
]

wasm = [
    "scsys-actors/wasm",
    "scsys-core/default"
]

actors = ["scsys-actors"]
core = ["scsys-core/default"]
derive = ["scsys-derive"]
gen = ["scsys-gen/default"]
macros = ["scsys-macros"]

extras = ["config"]

config = ["config/default"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dev-dependencies]
serde = { features = ["derive"], version = "1" }
serde_json = "1"

[dependencies]
config = { optional = true, version = "0.13" }

scsys-actors = { features = ["wasm"], optional = true, path = "../actors", version = "0.1.41" }
scsys-core = { features = [], optional = true, path = "../core", version = "0.1.41" }
scsys-derive = { features = [], optional = true, path = "../derive", version = "0.1.41" }
scsys-gen = { features = ["wasm"], optional = true, path = "../gen", version = "0.1.41" }
scsys-macros = { features = [], optional = true, path = "../macros", version = "0.1.41" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
