[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.23" # TODO: Update the package version

[features]
default = ["core", "crypto"]
full = ["core", "crypto", "derive", "macros", "extras"]

core = ["scsys-core"]
crypto = ["scsys-crypto"]
derive = ["scsys-derive"]
macros = ["scsys-macros"]

extras = []

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
anyhow = "1.0.65"
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], version = "2.4.0" }
chrono = "0.4.22"
config = "0.13.2"
futures = "0.3.24"
glob = "0.3.0"
hex = "0.4.3"
log = "0.4.17"
nom = "7.1.1"
rand = { features = ["getrandom", "serde1"], version = "0.8.5" }
ring = "0.16.20"
serde = { features = ["derive"], version = "1.0.147" }
serde_json = "1.0.87"
strum = { features = ["derive"], version = "0.24.1" }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
url = "2.3.1"

[dependencies.scsys-core]
optional = true
path = "../core"
version = "0.1.22"

[dependencies.scsys-crypto]
optional = true
path = "../crypto"
version = "0.1.22"

[dependencies.scsys-derive]
optional = true
path = "../derive"
version = "0.1.22" # TODO: Update feature versioning

[dependencies.scsys-macros]
optional = true
path = "../macros"
version = "0.1.22" # TODO: Update feature versioning

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
