[package]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
keywords = ["blockchain", "primitives", "scsys"]
name = "scsys"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "actors",
    "core",
    "gen",
]
full = [
    "actors",
    "core",
    "gen",
    "derive", 
    "macros", 
    "extras"
]

wasm = [
    "scsys-actors/wasm",
    "scsys-core/wasm",
    "scsys-gen/wasm"
]

actors = ["scsys-actors/default"]
core = ["scsys-core/default"]
derive = ["scsys-derive"]
gen = ["scsys-gen/default"]
macros = ["scsys-macros"]

extras = ["config"]

config = ["config/default"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[dependencies]
config = { optional = true, version = "0.13" }

scsys-actors = { features = ["wasm"], optional = true, path = "../actors", version = "0.1.41" }
scsys-core = { features = ["wasm"], optional = true, path = "../core", version = "0.1.41" }
scsys-derive = { features = [], optional = true, path = "../derive", version = "0.1.41" }
scsys-gen = { features = ["wasm"], optional = true, path = "../gen", version = "0.1.41" }
scsys-macros = { features = [], optional = true, path = "../macros", version = "0.1.41" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
