[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
name = "scsys"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "actors",
    "core",
]
full = [
    "actors",
    "core",
    "derive",
    "gen",
    "extras"
]

wasi = []
wasm = []

actors = [
    "scsys-actors"
]
core = [
    "scsys-core"
]
derive = [
    "scsys-derive", 
    "macros"
]
gen = [
    "scsys-generate"
]
macros = ["scsys-macros"]

extras = [

]


[lib]
bench = true
crate-type = ["cdylib", "rlib"]
test = true

[build-dependencies]

[dependencies]
scsys-actors = { features = [], optional = true, path = "../actors", version = "0.2.0" }
scsys-core = { features = [], optional = true, path = "../core", version = "0.2.0" }
scsys-derive = { features = [], optional = true, path = "../derive", version = "0.2.0" }
scsys-generate = { features = [], optional = true, path = "../generate", version = "0.2.0" }
scsys-macros = { features = [], optional = true, path = "../macros", version = "0.2.0" }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
