[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
name = "scsys"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "actors",
    "stores",
]
full = [
    "actors",
    "serde",
    "stores",
    "derive",
    "extras"
]

wasi = []
wasm = []

actors = [
    "dep:scsys-actors"
]

derive = [
    "dep:scsys-derive", 
    "macros"
]

macros = [
    "dep:scsys-macros"
]

stores = [
    "dep:scsys-stores"
]

extras = [

]

serde = [
    "scsys-core/serde"
]


[lib]
bench = true
crate-type = ["cdylib", "rlib"]
test = true

[[example]]
name = "messages"
required-features = ["actors"]

[[test]]
name = "derive"
required-features = ["derive"]


[build-dependencies]

[dependencies]
scsys-actors = { features = [], optional = true, path = "../actors", version = "0.2.0" }
scsys-core = { path = "../core", version = "0.2.0" }
scsys-derive = { features = [], optional = true, path = "../derive", version = "0.2.0" }
scsys-macros = { features = [], optional = true, path = "../macros", version = "0.2.0" }
scsys-stores = { features = [], optional = true, path = "../stores", version = "0.2.0" }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
