[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
name = "scsys"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "actors",
    "stores",
    "std",
]

full = [
    "actors",
    "derive",
    "extras",
    "stores",
]

wasi = []
wasm = []

actors = [
    "dep:scsys-actors"
]

derive = [
    "dep:scsys-derive", 
    "macros"
]

macros = [
    "dep:scsys-macros"
]

stores = [
    "dep:scsys-stores"
]

extras = [
    "serde",
    "tokio",
]

serde = [
    "scsys-actors/serde",
    "scsys-core/serde",
    "scsys-stores/serde",
]

std = [
    "scsys-core/std",
    "scsys-actors/std",
]

tokio = [
    "scsys-actors/tokio",
]


[lib]
bench = true
crate-type = ["cdylib", "rlib"]
test = true

[[example]]
name = "messages"
required-features = ["actors"]

[[example]]
name = "params"
required-features = ["derive"]


[[test]]
name = "derive"
required-features = ["serde", "derive"]


[build-dependencies]

[dependencies]
scsys-actors = { optional = true, path = "../actors", version = "0.2.1" }
scsys-core = { path = "../core", version = "0.2.1" }
scsys-derive = { optional = true, path = "../derive", version = "0.2.1" }
scsys-macros = { optional = true, path = "../macros", version = "0.2.1" }
scsys-stores = { optional = true, path = "../stores", version = "0.2.1" }

[dev-dependencies]
serde = { features = ["derive"], version = "1" }
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
