[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://scattered-systems.github.io/scsys/"
keywords = ["blockchain", "primitives", "scsys"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.12" # TODO: Update the package version

[features]
default = ["core", "external"]
full = ["core", "derive", "external", "macros"]

core = ["scsys-core"]
derive = ["scsys-derive"]
macros = ["scsys-macros"]

external = ["bson", "chrono", "config"]
bson = ["bson/default", "bson/chrono-0_4", "bson/serde_with", "bson/uuid-0_8"]
chrono = ["chrono/default"]
config = ["config/default"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], optional = true, version = "2.3.0" }
chrono = { optional = true, version = "0.4.19" }
config = { optional = true, version = "0.13.1" }

[dependencies.scsys-core]
optional = true
path = "../core"
version = "0.1.2"

[dependencies.scsys-derive]
optional = true
path = "../derive"
version = "0.1.1"

[dependencies.scsys-macros]
optional = true
path = "../macros"
version = "0.1.1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]