[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
name = "scsys"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "actors",
    "stores",
    "std",
]

full = [
    "default",
    "derive",
    "rand",
    "serde",
    "tokio",
]

actors = [
    "dep:scsys-actors"
]

derive = [
    "dep:scsys-derive", 
    "macros"
]

macros = [
    "dep:scsys-macros"
]

rand = [
    "scsys-core/rand",
]

serde = [
    "scsys-actors/serde",
    "scsys-core/serde",
    "scsys-stores/serde",
]

std = [
    "scsys-actors/std",
    "scsys-core/std",
    "scsys-stores/std",
]

stores = [
    "dep:scsys-stores"
]

tokio = [
    "scsys-actors/tokio",
]

[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[example]]
name = "derive"
required-features = ["derive", "serde"]

[[example]]
name = "messages"
required-features = ["actors"]

[[example]]
name = "params"
required-features = ["derive"]

[build-dependencies]

[dependencies]
scsys-core = { path = "../core", version = "0.2.2" }

scsys-actors = { optional = true, path = "../actors", version = "0.2.2" }
scsys-derive = { optional = true, path = "../derive", version = "0.2.2" }
scsys-macros = { optional = true, path = "../macros", version = "0.2.2" }
scsys-stores = { optional = true, path = "../stores", version = "0.2.2" }

[dev-dependencies]
serde = { features = ["derive"], version = "1" }
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
