[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
keywords.workspace = true
name = "scsys"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "std",
]

full = [
    "default",
    "actors",
    "derive",
    "rand",
    "serde",
    "tokio",
]

# *** [FF] Crates ***

actors = [
    "dep:scsys-actors",
]

derive = [
    "dep:scsys-derive", 
    "macros",
]

macros = [
    "dep:scsys-macros",
]

# *** [FF] Dependencies ***
alloc = [
    "scsys-actors?/alloc",
    "scsys-core/alloc",
]
rand = [
    "scsys-core/rand",
]

serde = [
    "scsys-actors?/serde",
    "scsys-core/serde",
]

tokio = [
    "scsys-actors?/tokio",
]
# *** [FF] Environments ***

std = [
    "scsys-actors?/std",
    "scsys-core/std",
]

wasi = [
    "scsys-actors?/wasi",
    "scsys-core/wasi",
]

wasm = [
    "scsys-actors?/wasm",
    "scsys-core/wasm",
]


[lib]
bench = true
crate-type = ["cdylib", "rlib"]
doctest = true
test = true

[[example]]
name = "derive"
required-features = ["derive", "serde"]

[[example]]
name = "messages"
required-features = ["actors"]

[[example]]
name = "params"
required-features = ["derive"]

[build-dependencies]

[dependencies.scsys-actors]
optional = true
path = "../actors"
version = "0.2.3"

[dependencies.scsys-core]
path = "../core"
version = "0.2.3"

[dependencies.scsys-derive]
optional = true
path = "../derive"
version = "0.2.3"

[dependencies.scsys-macros]
optional = true
path = "../macros"
version = "0.2.3"

[dev-dependencies]
serde = { features = ["derive"], version = "1" }
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
