[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "MIT"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.28" # TODO: Update the package version

[features]
default = ["core", "crypto"]
full = ["agents", "core", "crypto", "derive", "macros", "extras"]

agents = ["scsys-agents"]
core = ["scsys-core"]
crypto = ["scsys-crypto"]
derive = ["scsys-derive"]
macros = ["scsys-macros"]

extras = ["bson", "chrono", "config", "rand"]
bson = ["bson/default", "bson/chrono-0_4", "bson/serde_with", "bson/uuid-0_8"]
chrono = ["chrono/default"]
config = ["config/default"]
rand = ["rand/default"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], optional = true, version = "2.4.0" }
chrono = { optional = true, version = "0.4.22" }
config = { optional = true, version = "0.13.2" }
rand = { features = [], optional = true, version = "0.8.5" }

[dependencies.scsys-agents]
optional = true
path = "../agents"
version = "0.1.28"

[dependencies.scsys-core]
optional = true
path = "../core"
version = "0.1.28"

[dependencies.scsys-crypto]
optional = true
path = "../crypto"
version = "0.1.28"

[dependencies.scsys-derive]
optional = true
path = "../derive"
version = "0.1.28" # TODO: Update feature versioning

[dependencies.scsys-macros]
optional = true
path = "../macros"
version = "0.1.28" # TODO: Update feature versioning

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]
