[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)", "Scattered-Systems (https://github.com/scattered-systems)"]
categories = []
description = "scsys lays the foundation for the Scattered-Systems ecosystem, delivering critical primitives throughout"
edition = "2021"
homepage = "https://github.com/scattered-systems/scsys/wiki"
keywords = ["blockchain", "primitives", "scsys"]
license = "Apache-2.0"
name = "scsys"
readme = "README.md"
repository = "https://github.com/scattered-systems/scsys"
version = "0.1.35" # TODO: Update the package version

[features]
default = [
    "actors",
    "core",
    "crypto",
    "derive",
    "gen",
    "macros"
]
full = [
    "actors",
    "core",
    "crypto",
    "gen",
    "derive", 
    "macros", 
    "extras", 
    "wasm"
]

wasm = []
wasm-ext = [
    "scsys-crypto/wasm-ext"
]

actors = ["scsys-actors"]
core = ["scsys-core"]
crypto = ["scsys-crypto/full"]
derive = ["scsys-derive"]
gen = ["scsys-gen/full"]
macros = ["scsys-macros"]

extras = ["bson", "chrono", "config"]
bson = ["bson/default", "bson/chrono-0_4", "bson/serde_with", "bson/uuid-0_8"]
chrono = ["chrono/default"]
config = ["config/default"]

[lib]
crate-type = ["cdylib", "rlib"]
test = true

[dependencies]
bson = { features = ["chrono-0_4", "serde_with", "uuid-0_8"], optional = true, version = "2.4.0" }
chrono = { optional = true, version = "0.4.22" }
config = { optional = true, version = "0.13.2" }

scsys-actors = { features = [], optional = true, path = "../actors", version = "0.1.35" }
scsys-core = { features = [], optional = true, path = "../core", version = "0.1.35" }
scsys-crypto = { features = ["full"], optional = true, path = "../crypto", version = "0.1.35" }
scsys-derive = { features = [], optional = true, path = "../derive", version = "0.1.35" }
scsys-gen = { features = ["full"], optional = true, path = "../gen", version = "0.1.35" }
scsys-macros = { features = [], optional = true, path = "../macros", version = "0.1.35" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]
